# Generated by Django 5.0.4 on 2024-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_champ', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ModelToto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_champ', models.CharField(max_length=128)),
            ],
        ),
    ]
