# Generated by Django 5.0.4 on 2024-06-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteApp', '0003_souscategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venteApp.souscategorie'),
        ),
    ]
